/*!
file:	word_generator.c
author:	Wong Man Cong
		Lee Fu Sheng Roy
		Phua Tze Cheng Jennifer
		Thea Sea
		Nicole Wong

email:	w.mancong@digipen.edu
		f.lee@digipen.edu
		p.tzechengjennifer@digipen.edu
		thea.sea@digipen.edu
		n.wong@digipen.edu


@brief	This file contains a function as a random word generator.
		This is implemented by arrays.

	Copyright © 2020 DigiPen, All rights reserved.
*//*____________________________________________________________*/

#include "word_generator.h" //this is where the function prototype will be
#include "common_headers.h"

FileData themes;
unsigned word_generator_index = 0, max_words = 0;

/*!
@brief	loading the .txt files for the words to be generated by the theme, Animals
@param	totalWords: the number of words set to be displayed to the player, that varies with level and difficulty
*//*____________________________________________*/
void InitAnimals(unsigned totalWords)
{
	if (GetGameDifficulty() == EASY)
		themes = ReadFixedRandom("Assets/Words/animals_easy.txt", totalWords);
	else
		themes = ReadFixedRandom("Assets/Words/animals_hard.txt", totalWords);
}

/*!
@brief	loading the .txt files for the words to be generated by the theme, Food
@param	totalWords: the number of words set to be displayed to the player, that varies with level and difficulty
*//*____________________________________________*/
void InitFood(unsigned totalWords)
{
	if (GetGameDifficulty() == EASY)
		themes = ReadFixedRandom("Assets/Words/food_easy.txt", totalWords);
	else
		themes = ReadFixedRandom("Assets/Words/food_hard.txt", totalWords);
}

/*!
@brief	loading the .txt files for the words to be generated by the theme, Colours
@param	totalWords: the number of words set to be displayed to the player, that varies with level and difficulty
*//*____________________________________________*/
void InitColours(unsigned totalWords)
{
	if (GetGameDifficulty() == EASY)
		themes = ReadFixedRandom("Assets/Words/colours_easy.txt", totalWords);
	else
		themes = ReadFixedRandom("Assets/Words/colours_hard.txt", totalWords);
}

/*!
@brief	loading the .txt files for the words to be generated by the theme, Cities
@param	totalWords: the number of words set to be displayed to the player, that varies with level and difficulty
*//*____________________________________________*/
void InitCities(unsigned totalWords)
{
	if (GetGameDifficulty() == EASY)
		themes = ReadFixedRandom("Assets/Words/cities_easy.txt", totalWords);
	else
		themes = ReadFixedRandom("Assets/Words/cities_hard.txt", totalWords);
}

/*!
@brief	loading the .txt files for the words to be generated by the theme, Sports
@param	totalWords: the number of words set to be displayed to the player, that varies with level and difficulty
*//*____________________________________________*/
void InitSports(unsigned totalWords)
{
	if (GetGameDifficulty() == EASY)
		themes = ReadFixedRandom("Assets/Words/sports_easy.txt", totalWords);
	else
		themes = ReadFixedRandom("Assets/Words/sports_hard.txt", totalWords);
}

/*!
@brief	function that returns int k: the row number (of type int) containing the word to be randomly chosen
param: void
*//*____________________________________________*/
int RandomWord(void)
{
	int i;
	int k;

	i = (int)themes->rows; //change this value when the number of elements change
	k = 0;
	srand((unsigned)time(NULL));
	k = CP_Random_RangeInt(0, themes->rows);
	return k;
}

/*!
@brief	function to swap pointers
@param:	void
*//*____________________________________________*/
void WordShuffle(void)
{
	unsigned max_word = themes->rows - 1;
	for (unsigned i = 0; i < themes->rows; ++i)
	{
		int random_index = CP_Random_RangeInt(0, max_word);
		// swap pointers
		char* tmp_ptr = themes->str[i];
		themes->str[i] = themes->str[random_index];
		themes->str[random_index] = tmp_ptr;
	}
}

/*!
@brief	setting a switch case to display the correct theme .txt files to each level
@param	theme: the theme of words to be displayed, either animals, food, colours, sports or cities
		totalWords: the number of words set to be displayed to the player, that varies with level and difficulty
*//*____________________________________________*/
void InitTheme(WordTheme theme, unsigned totalWords)
{
	switch (theme)
	{
		case ANIMALS:
		{
			InitAnimals(totalWords);
			break;
		}
		
		case FOOD:
		{
			InitFood(totalWords);
			break;
		}

		case CITIES:
		{
			InitCities(totalWords);
			break;
		}

		case SPORTS:
		{
			InitSports(totalWords);
			break;
		}

		case COLOURS:
		{
			InitColours(totalWords);
			break;
		}
	}
	word_generator_index = 0;
	max_words = totalWords;
	WordShuffle();
}

/*!
@brief	getter function for current enemy word
@param	void
*//*____________________________________________*/
char* GetRandomWord(void)
{
	return themes->str[CP_Random_RangeInt(0, themes->rows)];
}

/*!
@brief	getter function for next enemy word
@param	void
*//*____________________________________________*/
char* GetNextWord(void)
{
	if (word_generator_index >= max_words)
		return "";
	return themes->str[word_generator_index++];
}

/*!
@brief	getter function for current enemy word index
@param	void
*//*____________________________________________*/
unsigned GetWordGenCurrentIndex(void)
{
	return word_generator_index;
}

/*!
@brief	freeing file data to prevent memory leak
@param	void
*//*____________________________________________*/
void FreeWordGenerator(void)
{
	FreeFileData(&themes);
}
